#!/usr/bin/env python3
"""
Map Calibration Script for Odin ROS Driver
地图坐标系校准脚本

Computes T_real_map_device_map: the rigid transform that aligns
the device's map frame to the real-world defined map origin,
using SVD (Horn's method) on matched control point positions.

The script uses TF lookup (map → odin1_base_link) to get the device's
estimate of position in its map frame, then compares with ground truth.

Usage:
    # Make sure the odin driver is running in relocalization mode (custom_map_mode: 2)
    # and relocalization has succeeded before running this script.
    ros2 run odin_ros_driver map_calibration.py
    # or:
    python3 script/map_calibration.py

Requirements:
    ROS 2 Jazzy with tf2_ros
"""

import sys
import os
import time
import threading
import numpy as np
import yaml
from datetime import datetime

import rclpy
from rclpy.node import Node
from tf2_ros import Buffer, TransformListener
from rclpy.time import Time


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_DIR = os.path.join(os.path.dirname(SCRIPT_DIR), 'config')
CALIBRATION_FILE = os.path.join(CONFIG_DIR, 'map_calibration.yaml')

COLLECTION_DURATION = 5.0  # seconds to collect TF data per point
LOOKUP_RATE = 20.0  # Hz for TF lookup


def compute_rigid_transform_svd(src_points, dst_points):
    """
    Compute optimal rigid transformation (rotation + translation) using SVD.
    Horn's method: finds T such that dst ≈ R * src + t

    Args:
        src_points: Nx3 numpy array (device map positions from TF lookup)
        dst_points: Nx3 numpy array (ground truth / real map positions)

    Returns:
        R: 3x3 rotation matrix
        t: 3x1 translation vector
        T: 4x4 homogeneous transformation matrix (T_real_map_device_map)
        rmse: root mean square error
    """
    assert src_points.shape == dst_points.shape
    assert src_points.shape[0] >= 3, "At least 3 points required"

    centroid_src = src_points.mean(axis=0)
    centroid_dst = dst_points.mean(axis=0)

    src_centered = src_points - centroid_src
    dst_centered = dst_points - centroid_dst

    H = src_centered.T @ dst_centered

    U, S, Vt = np.linalg.svd(H)
    V = Vt.T

    # Ensure proper rotation (det(R) = +1, not reflection)
    d = np.linalg.det(V @ U.T)
    sign_matrix = np.diag([1, 1, d])
    R = V @ sign_matrix @ U.T

    t = centroid_dst - R @ centroid_src

    T = np.eye(4)
    T[:3, :3] = R
    T[:3, 3] = t

    # Compute RMSE
    transformed = (R @ src_points.T).T + t
    errors = np.linalg.norm(transformed - dst_points, axis=1)
    rmse = np.sqrt(np.mean(errors ** 2))

    return R, t, T, rmse


def check_collinearity(points):
    """Check if points are collinear (all on the same line)."""
    if len(points) < 3:
        return True

    p0 = np.array(points[0])
    for i in range(1, len(points) - 1):
        for j in range(i + 1, len(points)):
            v1 = np.array(points[i]) - p0
            v2 = np.array(points[j]) - p0
            cross = np.cross(v1, v2)
            if np.linalg.norm(cross) > 1e-6:
                return False
    return True


def load_control_points(filepath):
    """Load control points from the YAML file."""
    if not os.path.exists(filepath):
        print(f"Error: Calibration file not found: {filepath}")
        print(f"Please create it first. See config/map_calibration.yaml template.")
        sys.exit(1)

    with open(filepath, 'r') as f:
        data = yaml.safe_load(f)

    if 'control_points' not in data or not data['control_points']:
        print("Error: No control_points defined in calibration file.")
        sys.exit(1)

    points = data['control_points']
    if len(points) < 3:
        print(f"Error: At least 3 control points required, got {len(points)}.")
        sys.exit(1)

    for i, pt in enumerate(points):
        if 'position' not in pt or len(pt['position']) != 3:
            print(f"Error: control_points[{i}] must have 'position' with [x, y, z].")
            sys.exit(1)

    positions = [pt['position'] for pt in points]
    if check_collinearity(positions):
        print("Error: Control points are collinear. Need at least 3 non-collinear points.")
        sys.exit(1)

    return points


def save_results(filepath, control_points, measured_points, T, rmse):
    """
    Save calibration results to YAML file.
    Preserves the upper section (control_points) and writes lower section.
    """
    with open(filepath, 'r') as f:
        original_content = f.read()

    lines = original_content.split('\n')
    upper_lines = []
    for line in lines:
        if line.startswith('measured_points:') or line.startswith('# ===== Measured Points'):
            break
        upper_lines.append(line)

    lower_section = []
    lower_section.append("# ===== Measured Points (Auto-generated by script) =====")
    lower_section.append("# 测量点（由脚本自动生成，请勿手动修改）")
    lower_section.append("# Positions in device map frame via TF lookup (map → odin1_base_link)")
    lower_section.append("# 通过TF查询获取的设备地图坐标系下位置（5秒平均值）")
    lower_section.append("measured_points:")
    for mp in measured_points:
        lower_section.append(f'  - name: "{mp["name"]}"')
        pos = mp['position']
        lower_section.append(f'    position: [{pos[0]:.6f}, {pos[1]:.6f}, {pos[2]:.6f}]')

    lower_section.append("")
    lower_section.append("# ===== Calibration Result (Auto-generated by script) =====")
    lower_section.append("# 校准结果（由脚本自动生成，请勿手动修改）")
    lower_section.append("# T_real_map_device_map: transforms device map positions to real map positions")
    lower_section.append("# P_real_map = T_calibration * P_device_map")
    lower_section.append("calibration_result:")
    lower_section.append("  valid: true")
    lower_section.append("  # 4x4 transformation matrix (row-major, nested list)")
    lower_section.append("  transform_matrix:")
    for i in range(4):
        row = T[i, :].tolist()
        lower_section.append(f"    - [{row[0]:.10f}, {row[1]:.10f}, {row[2]:.10f}, {row[3]:.10f}]")
    lower_section.append(f"  rmse: {rmse:.8f}")
    lower_section.append(f'  timestamp: "{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}"')
    lower_section.append("")

    result = '\n'.join(upper_lines) + '\n' + '\n'.join(lower_section)

    with open(filepath, 'w') as f:
        f.write(result)


def collect_tf_position(node, tf_buffer, duration):
    """Collect TF lookup samples for a duration and return average position."""
    positions = []
    end_time = time.time() + duration
    period = 1.0 / LOOKUP_RATE

    while time.time() < end_time:
        rclpy.spin_once(node, timeout_sec=0.01)
        try:
            transform = tf_buffer.lookup_transform(
                'map', 'odin1_base_link', Time())
            x = transform.transform.translation.x
            y = transform.transform.translation.y
            z = transform.transform.translation.z
            positions.append([x, y, z])
        except Exception:
            pass
        time.sleep(period)

    if not positions:
        return None, 0
    arr = np.array(positions)
    return arr.mean(axis=0).tolist(), len(positions)


def run_calibration(control_points):
    """Run calibration using TF lookup (ROS 2)."""
    rclpy.init()
    node = rclpy.create_node('map_calibration')
    tf_buffer = Buffer()
    tf_listener = TransformListener(tf_buffer, node)

    # Wait for TF to become available
    print("\n  Waiting for TF (map → odin1_base_link)...")
    print("  等待TF变换可用（map → odin1_base_link）...")
    timeout = 30.0
    start = time.time()
    tf_ready = False
    while time.time() - start < timeout:
        rclpy.spin_once(node, timeout_sec=0.1)
        try:
            tf_buffer.lookup_transform('map', 'odin1_base_link', Time())
            tf_ready = True
            break
        except Exception:
            pass

    if not tf_ready:
        print("\n  ERROR: TF (map → odin1_base_link) not available after 30s!")
        print("  Make sure relocalization has succeeded.")
        print("  错误：30秒内未检测到 map→odin1_base_link TF！请确保重定位已成功。")
        node.destroy_node()
        rclpy.shutdown()
        sys.exit(1)

    print("  ✅ TF available. Ready for calibration.")

    measured_points = []

    print("\n" + "=" * 60)
    print("  Map Calibration - Point Collection (via TF)")
    print("  地图校准 - 控制点数据采集（通过TF查询）")
    print("=" * 60)
    print(f"\n  Total control points: {len(control_points)}")
    print(f"  Collection duration per point: {COLLECTION_DURATION}s")
    print(f"  Data source: TF lookup (map → odin1_base_link)\n")

    for i, cp in enumerate(control_points):
        name = cp.get('name', f'point_{i+1}')
        pos = cp['position']

        print(f"\n--- Point {i+1}/{len(control_points)}: {name} ---")
        print(f"    Target position (ground truth): [{pos[0]:.3f}, {pos[1]:.3f}, {pos[2]:.3f}]")
        input(f"\n    Move device to this point, then press Enter...")
        print(f"    Collecting TF data for {COLLECTION_DURATION} seconds...")

        avg_pos, count = collect_tf_position(node, tf_buffer, COLLECTION_DURATION)

        if avg_pos is None:
            print("    ERROR: No TF data collected! Check that relocalization succeeded.")
            print("    错误：未采集到TF数据！请检查重定位是否成功。")
            node.destroy_node()
            rclpy.shutdown()
            sys.exit(1)

        print(f"    Collected {count} samples.")
        print(f"    Measured position (device map): [{avg_pos[0]:.6f}, {avg_pos[1]:.6f}, {avg_pos[2]:.6f}]")

        measured_points.append({
            'name': name,
            'position': avg_pos
        })

    node.destroy_node()
    rclpy.shutdown()
    return measured_points


def main():
    print("\n  Odin Map Calibration Tool (TF-based)")
    print("  Odin 地图坐标系校准工具（基于TF查询）\n")
    print(f"  Config file: {CALIBRATION_FILE}\n")

    control_points = load_control_points(CALIBRATION_FILE)
    print(f"  Loaded {len(control_points)} control points.")

    measured_points = run_calibration(control_points)

    # SVD: find T_real_map_device_map
    # src = device map positions (from TF lookup)
    # dst = ground truth positions (real map, from YAML)
    src_pts = np.array([mp['position'] for mp in measured_points])
    dst_pts = np.array([cp['position'] for cp in control_points])

    print("\n" + "=" * 60)
    print("  Computing calibration transform (SVD)...")
    print("  计算校准变换 T_real_map_device_map（SVD）...")
    R, t, T, rmse = compute_rigid_transform_svd(src_pts, dst_pts)

    print(f"\n  Rotation matrix R:")
    for row in R:
        print(f"    [{row[0]:10.6f}, {row[1]:10.6f}, {row[2]:10.6f}]")
    print(f"\n  Translation t: [{t[0]:.6f}, {t[1]:.6f}, {t[2]:.6f}]")
    print(f"\n  RMSE: {rmse:.6f} meters")

    if rmse > 0.1:
        print(f"\n  ⚠️  WARNING: RMSE ({rmse:.4f}m) is above 0.1m threshold!")
        print(f"     This may indicate measurement errors or incorrect control points.")
    else:
        print(f"\n  ✅ Calibration RMSE is within acceptable range.")

    save_results(CALIBRATION_FILE, control_points, measured_points, T, rmse)
    print(f"\n  Results saved to: {CALIBRATION_FILE}")
    print(f"\n  Calibration complete! Restart the driver to apply.")
    print(f"  校准完成！重启驱动以应用校准。")
    print("=" * 60 + "\n")


if __name__ == '__main__':
    main()
